"""Add one open item: Stave Delivery's E-Verify module is not visible in Paycom.

open_items is hand-curated by Shobhit and no scheduled job writes to it. This
script exists because Shobhit asked for this specific item to be recorded after
raising it with the implementer. It inserts exactly one row and never updates
or deletes an existing one.

Grounded in the sent mail of 19 Aug 2026, 11:20 UTC (message 1a019c0c59c7040f),
subject "Historical Data Issue E-Verify Cases not found on the Paycom - Stave
Delivery", to Mercedes Hallback, copying Shruti Singhal, Rohit Kaushik and
Priyanshu Sinha. Nothing in the description goes beyond what that mail says or
what the catalog/status tables show.

Fields follow the pattern of the 19 Aug client-raised items (ids 20-22):
severity 'Needs action', pending_for 'Implementation', assignee = the person
carrying it to the client, due date three days out.
"""
import sys

from supabase_helper import connect

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

TITLE = "Stave Delivery - E-Verify module not found in Paycom"

DESCRIPTION = (
    "Raised with the client: email to Mercedes Hallback on 19 Aug 2026, copying "
    "Shruti, Rohit and Priyanshu, subject 'Historical Data Issue E-Verify Cases "
    "not found on the Paycom - Stave Delivery'. The E-Verify Cases module could "
    "not be found in Paycom at all. The mail asks two things: whether the client "
    "has subscribed to the module, and - if they have - why the E-Verify cases "
    "grid is not visible on the UI. Now waiting on the client's answer through "
    "Mercedes. "
    "Impact on historical collection: the Paycom catalog has exactly two E-Verify "
    "reports - 'E-Verify Cases (grid export)' and 'E-Verify Case Details (all "
    "cases)' - and both are still Pending for this client. Neither can be "
    "collected while the module is invisible, so they are blocked rather than "
    "merely outstanding. "
    "If the answer comes back that the client never subscribed, the right close-out "
    "is to mark those two rows Not applicable rather than leave them Pending "
    "forever, since no report setting can produce data for a module the client "
    "does not have. Do not mark them off before the client confirms - unlike the "
    "InnovDel timecard case, this has not been shown to be an absent-data problem "
    "yet; it may still be a subscription or permission one."
)


def main():
    conn = connect()
    cur = conn.cursor()

    cur.execute(
        "select column_default, is_identity from information_schema.columns "
        "where table_name = 'open_items' and column_name = 'id'")
    default, is_identity = cur.fetchone()
    autogen = bool(default) or is_identity == "YES"
    print(f"id autogenerated: {autogen} (default={default!r}, identity={is_identity})")

    cur.execute("select id, status from open_items where title = %s", (TITLE,))
    existing = cur.fetchall()
    if existing:
        raise SystemExit(f"An item with this title already exists ({existing}) "
                         "- not inserting a duplicate.")

    cur.execute("select count(*) from open_items")
    before = cur.fetchone()[0]

    values = ("Needs action", TITLE, DESCRIPTION, "Open", "2026-08-19",
              "2026-08-22", "Implementation", "Mercedes Hallback")

    if autogen:
        cur.execute(
            "insert into open_items (severity, title, description, status, "
            "date_added, due_date, pending_for, assignee) "
            "values (%s,%s,%s,%s,%s,%s,%s,%s) returning id", values)
    else:
        cur.execute(
            "insert into open_items (id, severity, title, description, status, "
            "date_added, due_date, pending_for, assignee) "
            "select coalesce(max(id), 0) + 1, %s,%s,%s,%s,%s,%s,%s,%s "
            "from open_items returning id", values)

    new_id = cur.fetchone()[0]

    cur.execute("select count(*) from open_items")
    after = cur.fetchone()[0]
    if after != before + 1:
        conn.rollback()
        raise SystemExit(f"Row count went {before} -> {after}, expected +1 "
                         "- rolled back.")

    conn.commit()
    print(f"inserted open_items id={new_id}  ({before} -> {after} rows)")

    cur.execute(
        "select id, severity, title, status, date_added, due_date, pending_for, assignee "
        "from open_items where id = %s", (new_id,))
    print("\nNEW ROW:", cur.fetchone())

    print("\nOpen items still Open:")
    cur.execute("select id, severity, title, assignee from open_items "
                "where status = 'Open' order by id")
    for row in cur.fetchall():
        print("  ", row)

    cur.close()
    conn.close()


if __name__ == "__main__":
    main()
